steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/askai-health-backend:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/askai-health-backend:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "askai-health-backend"
      - "--image"
      - "gcr.io/$PROJECT_ID/askai-health-backend:$COMMIT_SHA"
      - "--region"
      - "asia-south1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
      - "--set-env-vars"
      - "ML_SERVICE_URL=https://ml-service-358309174344.asia-south1.run.app,NODE_ENV=production,FRONTEND_ORIGIN=https://youth-mental-wellness.vercel.app"

images:
  - "gcr.io/$PROJECT_ID/askai-health-backend:$COMMIT_SHA"
