# -*- coding: utf-8 -*-
"""Improved Redaction Helper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yrmu4RQ3TsHupBRxKliIL6tvulzHh8lX
"""

import re

# A more robust list of PII patterns using regular expressions.
PII_PATTERNS = [
    # Patterns for names, including middle initials and multiple names.
    # E.g., "John Doe", "Mary Anne Smith", "P. J. Harris"
    r"\b[A-Z]\w+ (?:\. |[A-Z]\w+ )+[A-Z]\w+\b",

    # 10-digit phone numbers, with or without spaces/hyphens.
    # E.g., "9876543210", "987-654-3210", "987 654 3210"
    r"\b\d{3}[-.\s]?\d{3}[-.\s]?\d{4}\b",

    # Email addresses.
    # E.g., "user@example.com", "first.last@mail.co.uk"
    r"\b[\w\.-]+@[\w\.-]+\.\w+\b",

    # Dates in various formats (MM/DD/YYYY, DD-MM-YY, etc.).
    r"\b\d{1,4}[/.-]\d{1,2}[/.-]\d{2,4}\b"
]

def redact(text):
    """
    Replaces all matches of PII patterns in a given string with "[REDACTED]".
    """
    for p in PII_PATTERns:
        text = re.sub(p, "[REDACTED]", text)
    return text

if __name__ == "__main__":
    # Test the improved redaction with a sample string containing various PII formats.
    sample = "Hi, I'm Dr. Jane Marie Smith. My phone number is 987-654-3210. You can email me at jmsmith@corp.org, and my birthday is 05-02-1985. I have an old number 9876543210 and a date 10/21/24."

    print("Original text:")
    print(sample)
    print("\nRedacted text:")
    print(redact(sample))